import { v4 as uuidv4 } from 'uuid';
import type { Exercise } from '@/types';

const now = Date.now();

export const seedExercises: Exercise[] = [
  // CHEST (15+)
  {
    id: uuidv4(),
    name: 'Dumbbell Bench Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbells', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions:
      'Lie flat on bench, press dumbbells up from chest level. Lower with control.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Incline Dumbbell Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Set bench to incline. Press dumbbells up and slightly forward.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Crossover',
    muscleGroups: ['chest'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Stand in center, pull cables together in a hugging motion.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Pec Deck Machine',
    muscleGroups: ['chest'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Sit upright, push handles forward with chest squeeze.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Floor Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Lie on back on floor, press dumbbells up. Range limited by floor.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Push-up (Standard)',
    muscleGroups: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Body straight, lower chest to ground, press back up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Assisted Dip Machine',
    muscleGroups: ['chest', 'triceps'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Sit in machine, press down. Machine assists with counterweight.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Landmine Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell', 'landmine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Hold bar at shoulder, press diagonally forward and up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Svend Press',
    muscleGroups: ['chest'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Hold two dumbbells vertically at chest, press forward.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Fly High',
    muscleGroups: ['chest'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Set cables high, pull down and together in arc motion.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Fly Mid',
    muscleGroups: ['chest'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Set cables at shoulder height, pull together in arc.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Fly Low',
    muscleGroups: ['chest'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Set cables low, pull up and together in arc motion.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Decline Dumbbell Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Set bench to decline, press dumbbells from chest.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Close-grip Bench Press (EZ Bar)',
    muscleGroups: ['triceps', 'chest'],
    equipment: ['barbell', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Hands closer than shoulder width, press up and down.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Machine Chest Press',
    muscleGroups: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Sit upright, push handles forward.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // BACK (15+)
  {
    id: uuidv4(),
    name: 'Lat Pulldown (Wide)',
    muscleGroups: ['back', 'lats'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Wide grip, pull bar down to upper chest.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Lat Pulldown (Close)',
    muscleGroups: ['back', 'lats'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Close grip, pull bar down to mid-chest.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Lat Pulldown (Reverse/Underhand)',
    muscleGroups: ['back', 'lats'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Underhand grip, pull bar down to mid-chest.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Seated Cable Row',
    muscleGroups: ['back'],
    secondaryMuscles: ['lats'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Sit upright, pull handle toward torso, squeeze shoulder blades.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Dumbbell Row',
    muscleGroups: ['back'],
    secondaryMuscles: ['lats'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Knee on bench, row dumbbell up to hip.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Chest-supported Row',
    muscleGroups: ['back'],
    secondaryMuscles: ['lats'],
    equipment: ['dumbbells', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Lean on incline bench, row dumbbells up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Face Pull',
    muscleGroups: ['shoulders', 'back'],
    secondaryMuscles: ['rear delts'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Set rope at face height, pull rope toward face, spread ends.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Band Pull-apart',
    muscleGroups: ['back', 'shoulders'],
    equipment: ['resistance band'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Hold band at shoulder height, pull apart and together.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Straight-arm Pulldown',
    muscleGroups: ['lats', 'back'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Straight arms, pull cable down from above head to hips.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Meadows Row',
    muscleGroups: ['back', 'lats'],
    equipment: ['barbell'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'pull',
    instructions:
      'One end of barbell in corner, straddle bar, row to hip on one side.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'TRX Row',
    muscleGroups: ['back'],
    equipment: ['TRX'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Lean back, pull body toward handles.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Pull-through',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions:
      'Stand facing away, pull rope through legs, stand up with hip drive.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Reverse Fly',
    muscleGroups: ['back', 'shoulders'],
    secondaryMuscles: ['rear delts'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Slightly bent knees, fly arms out to sides in arc.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Shrug (Dumbbell)',
    muscleGroups: ['traps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Shrug shoulders up toward ears.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Shrug (Machine)',
    muscleGroups: ['traps'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Sit in machine, shrug up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // SHOULDERS (10+)
  {
    id: uuidv4(),
    name: 'Dumbbell Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Slight knee bend, raise dumbbells out to sides to shoulder height.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Lateral Raise',
    muscleGroups: ['shoulders'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Stand sideways to cable, raise handle out to side.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Front Raise',
    muscleGroups: ['shoulders'],
    equipment: ['dumbbells', 'barbell'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Raise weight in front of body to shoulder height.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Arnold Press',
    muscleGroups: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions:
      'Start with palms facing you, press up and rotate palms forward.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Dumbbell Shoulder Press',
    muscleGroups: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Seated or standing, press dumbbells from shoulders up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Machine Shoulder Press',
    muscleGroups: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Sit in machine, press handles forward and up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Upright Row (Cable)',
    muscleGroups: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Pull cable up to shoulder height, elbows high.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Rear Delt Fly Machine',
    muscleGroups: ['shoulders'],
    secondaryMuscles: ['back'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Sit facing machine, push handles out and back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Y-raise',
    muscleGroups: ['shoulders'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Raise dumbbells in Y shape above head.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // ARMS (15+)
  {
    id: uuidv4(),
    name: 'Hammer Curl',
    muscleGroups: ['biceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Neutral grip, curl dumbbells up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Incline Dumbbell Curl',
    muscleGroups: ['biceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Lean back on incline, curl dumbbells.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Curl',
    muscleGroups: ['biceps'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Curl cable handle with elbows tucked.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Preacher Curl',
    muscleGroups: ['biceps'],
    equipment: ['dumbbells', 'barbell'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Arms on preacher bench, curl weight.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Concentration Curl',
    muscleGroups: ['biceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Seated, curl single dumbbell, focus on squeeze.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Rope Pushdown',
    muscleGroups: ['triceps'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Push rope down, spread at bottom.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Overhead Cable Extension',
    muscleGroups: ['triceps'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Facing away from cable, extend rope overhead.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Skull Crusher (EZ Bar Light)',
    muscleGroups: ['triceps'],
    equipment: ['barbell'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Lying, lower bar to forehead, extend up. Use light weight.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Close-grip Push-up',
    muscleGroups: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Hands close together, lower to ground.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Reverse Curl',
    muscleGroups: ['biceps', 'forearms'],
    equipment: ['barbell', 'dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Overhand grip, curl weight.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Wrist Curl',
    muscleGroups: ['forearms'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Palms up on bench, curl wrists.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Band Curl',
    muscleGroups: ['biceps'],
    equipment: ['resistance band'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Stand on band, curl handles up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Machine Curl',
    muscleGroups: ['biceps'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Sit in machine, curl handles.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Tricep Dip (Assisted)',
    muscleGroups: ['triceps'],
    secondaryMuscles: ['chest'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Dip in assisted machine.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Kickback',
    muscleGroups: ['triceps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Knee on bench, extend arm back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // LEGS - INJURY SAFE ONLY (20+)
  {
    id: uuidv4(),
    name: 'Leg Press (Bilateral)',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    kneLoadLevel: 'medium',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'squat',
    instructions: 'Plant feet, push platform away. No deep knee flexion.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Leg Press (Unilateral)',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    kneLoadLevel: 'medium',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'squat',
    instructions: 'One leg at a time. Prevents knee twisting.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hip Thrust (Barbell)',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['barbell', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Back on bench, thrust hips up. Knees at 90 degrees.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hip Thrust (Dumbbell)',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['dumbbells', 'bench'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Back on bench, hold dumbbells, thrust hips.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hip Thrust (Banded)',
    muscleGroups: ['glutes'],
    equipment: ['resistance band'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Band around hips, thrust up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Romanian Deadlift',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: ['barbell', 'dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Slight knee bend, hinge at hips with straight back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Stiff-leg Deadlift',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: ['barbell', 'dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Nearly straight legs, hinge from hips.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hamstring Curl (Seated)',
    muscleGroups: ['hamstrings'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Seated, curl leg pad toward glutes.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hamstring Curl (Lying)',
    muscleGroups: ['hamstrings'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Lying face down, curl legs up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Leg Extension (Light)',
    muscleGroups: ['quads'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Seated, extend legs. Use light weight only.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Stationary Lunge',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'medium',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'squat',
    instructions: 'Step forward, lower until knees at 90 degrees.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Step-up (Low Box)',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'medium',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'squat',
    instructions: 'Step up on low box, control descent.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Banded Hip Abduction',
    muscleGroups: ['glutes'],
    equipment: ['resistance band'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Band above knees, spread legs out.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Clamshell',
    muscleGroups: ['glutes'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Side-lying, top knee opens up, mimicking clamshell.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Glute Bridge',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Lie on back, feet flat, thrust hips up.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Single-leg Glute Bridge',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'One leg off ground, thrust up with other leg.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Reverse Hyperextension',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'hinge',
    instructions: 'Belly on machine, raise legs behind.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Nordic Curl (Assisted)',
    muscleGroups: ['hamstrings'],
    equipment: ['band'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'pull',
    instructions: 'Kneeling, band assists as you lower forward.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Seated Calf Raise',
    muscleGroups: ['calves'],
    equipment: ['machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Seated, raise up on toes.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Standing Calf Raise',
    muscleGroups: ['calves'],
    equipment: ['barbell', 'dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'push',
    instructions: 'Stand, raise on toes.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // CORE (15+)
  {
    id: uuidv4(),
    name: 'Dead Bug',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Lie on back, opposite arm and leg extend.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Bird Dog',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'On hands and knees, extend opposite arm and leg.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Plank (Standard)',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Hold straight body position.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Plank (Side)',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Side plank hold.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Plank (RKC)',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Intense plank with maximum body tension.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Bear Crawl Hold',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Hands and feet on ground, hips level.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Pallof Press',
    muscleGroups: ['core'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Press cable away from chest, resist rotation.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Ab Wheel Rollout',
    muscleGroups: ['core'],
    equipment: ['ab wheel'],
    kneLoadLevel: 'low',
    backLoadLevel: 'medium',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Kneel, roll wheel out and back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cable Crunch (Light)',
    muscleGroups: ['core'],
    equipment: ['cable machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Light weight, crunch down.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Leg Raise (Hanging)',
    muscleGroups: ['core'],
    equipment: ['pull-up bar'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Hang from bar, raise legs.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Leg Raise (Lying)',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Lie on back, raise legs.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Mountain Climber (Slow)',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Plank position, drive knees slowly.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Hollow Body Hold',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Lie on back, body arched.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'McGill Curl-up',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'One leg bent, curl upper back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Suitcase Carry',
    muscleGroups: ['core'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'carry',
    instructions: 'Hold dumbbell at side, walk.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Farmers Carry (Light)',
    muscleGroups: ['core', 'traps'],
    equipment: ['dumbbells'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'carry',
    instructions: 'Hold dumbbells at sides, walk. Light weight.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Copenhagen Plank',
    muscleGroups: ['core'],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'core',
    instructions: 'Side plank with top leg pulled in.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },

  // CARDIO (10+)
  {
    id: uuidv4(),
    name: 'Treadmill Walk',
    muscleGroups: [],
    equipment: ['treadmill'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Walk at steady pace.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Treadmill Incline Walk',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['treadmill'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Walk on incline at steady pace.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Stationary Bike',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['stationary bike'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Steady pace cycling.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Elliptical',
    muscleGroups: ['quads', 'glutes', 'back'],
    equipment: ['elliptical'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Steady pace on elliptical.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Rowing Machine',
    muscleGroups: ['back', 'quads', 'hamstrings'],
    equipment: ['rowing machine'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Drive with legs, pull with back.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Stair Climber',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['stair climber'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Climb stairs at steady pace.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Outdoor Walk',
    muscleGroups: [],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Walk outdoors.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Pool Walking',
    muscleGroups: [],
    equipment: [],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Walk in shallow pool water.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Cycling (Outdoor)',
    muscleGroups: ['quads', 'glutes'],
    equipment: ['bicycle'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Ride bicycle outdoors.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: uuidv4(),
    name: 'Jump Rope (Low Impact)',
    muscleGroups: ['calves'],
    equipment: ['jump rope'],
    kneLoadLevel: 'low',
    backLoadLevel: 'low',
    injurySafe: true,
    movementPattern: 'cardio',
    instructions: 'Light, steady pace jumping.',
    isCustom: false,
    source: 'builtin',
    createdAt: now,
    updatedAt: now,
  },
];
